export const ROLES = {
  // Склад
  warehouse_director: {
    label: 'Директор склада',
    world: 'warehouse',
    canInvite: ['warehouse'],
    canApprove: true,
    canDelete: true,
    seeHistory: true,
    seeAnalytics: true,
    seeValuation: true,
    canIssue: true,
    canWriteOff: true,
    canPublicLink: true,
  },
  warehouse_deputy: {
    label: 'Зам директора склада',
    world: 'warehouse',
    canInvite: [],
    canApprove: false,
    canDelete: false,
    seeHistory: true,
    seeAnalytics: false,
    seeValuation: true,
    canIssue: true,
    canWriteOff: false,
    canPublicLink: true,
  },
  warehouse_staff: {
    label: 'Сотрудник склада',
    world: 'warehouse',
    canInvite: [],
    canApprove: false,
    canDelete: false,
    seeHistory: false,
    seeAnalytics: false,
    seeValuation: false,
    canIssue: true,
    canWriteOff: false,
    canPublicLink: true,
  },

  // Площадка
  producer: {
    label: 'Продюсер',
    world: 'production',
    canInvite: ['all'],
    seeAnalytics: true,
    seeValuation: true,
    uploadDocs: false,
    readOnly: true,
  },
  project_director: {
    label: 'Директор проекта',
    world: 'production',
    canInvite: ['production'],
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
  },
  project_deputy_upload: {
    label: 'Зам директора проекта (загрузка)',
    world: 'production',
    canInvite: [],
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
  },
  project_deputy: {
    label: 'Зам директора проекта',
    world: 'production',
    canInvite: [],
    uploadKpp: false,
    uploadScenario: false,
    uploadCallsheet: false,
  },
  set_admin: {
    label: 'Администратор площадки',
    world: 'production',
    uploadCallsheet: true,
  },
  assistant_director: {
    label: 'Помощник режиссёра-постановщика',
    world: 'production',
    uploadCallsheet: true,
  },
  director: {
    label: 'Режиссёр-постановщик',
    world: 'production',
    readAllDocs: true,
    readAllLists: true,
  },
  production_designer: {
    label: 'Художник-постановщик',
    world: 'production',
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
    ownLists: ['all'],
    seeAllLists: true,
  },
  art_director_assistant: {
    label: 'Ассистент художника-постановщика',
    world: 'production',
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
    ownLists: ['all'],
    seeAllLists: true,
  },
  props_master: {
    label: 'Реквизитор',
    world: 'production',
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
    ownLists: ['props', 'art_fill', 'dummy', 'auto', 'costumes'],
  },
  props_assistant: {
    label: 'Ассистент художника по реквизиту',
    world: 'production',
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
    ownLists: ['props', 'art_fill', 'dummy', 'auto', 'costumes'],
  },
  decorator: {
    label: 'Декоратор',
    world: 'production',
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
    ownLists: ['decoration', 'props', 'art_fill', 'dummy'],
  },
  costumer: {
    label: 'Костюмер',
    world: 'production',
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
    ownLists: ['costumes'],
  },
  costume_assistant: {
    label: 'Ассистент художника по костюмам',
    world: 'production',
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
    ownLists: ['costumes'],
  },
  makeup_artist: {
    label: 'Гримёр',
    world: 'production',
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
    ownLists: ['makeup'],
    seePurchaseReport: true,
  },
  stunt_coordinator: {
    label: 'Постановщик трюков',
    world: 'production',
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
    ownLists: ['stunts'],
  },
  pyrotechnician: {
    label: 'Пиротехник',
    world: 'production',
    uploadKpp: true,
    uploadScenario: true,
    uploadCallsheet: true,
    ownLists: ['pyrotechnics'],
  },
  gaffer: {
    label: 'Гафер',
    world: 'production',
    readDocs: ['kpp', 'scenario', 'callsheet'],
  },
  dop: {
    label: 'Оператор-постановщик',
    world: 'production',
    readDocs: ['kpp', 'scenario', 'callsheet'],
  },
  camera_mechanic: {
    label: 'Механик камеры',
    world: 'production',
    readDocs: ['kpp', 'callsheet'],
    noVersionNotify: true,
  },
  casting_director: {
    label: 'Кастинг-директор',
    world: 'production',
    readDocs: ['kpp', 'scenario', 'callsheet'],
  },
  casting_assistant: {
    label: 'Ассистент кастинг-директора',
    world: 'production',
    readDocs: ['kpp', 'scenario', 'callsheet'],
  },
  playback: {
    label: 'Плейбэкер',
    world: 'production',
    readDocs: ['kpp', 'callsheet'],
    noVersionNotify: true,
  },
  driver: {
    label: 'Водитель',
    world: 'production',
    readDocs: ['kpp', 'callsheet'],
    noVersionNotify: true,
  },
}
